
name: Npm Publish
on:
 push:
   branches: [ master ]
 types: [published]
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    — run: yarn install
    — run: npm publish — access public
  env:
    NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}